apiVersion: v1
kind: Service
metadata:
  name: client-service
spec:
  type: NodePort
  selector:
    app: client
  ports:
    - protocol: TCP
      port: 80 # Порт внутри кластера
      targetPort: 80 # Порт приложения в контейнере
      nodePort: 31212 # Внешний порт, на который проброшен трафик
